src/Codersmill/ArchiveBundle/Entity/Tag.php
<?php

namespace Codersmill\ArchiveBundle\Entity;

class Tag
{
	protected $id;

	protected $tag_name;

    protected $tag_desc;

    private $archives;

    public function __construct() {
        $this->archives = new \Doctrine\Common\Collections\ArrayCollection();
    }

    public function getArchives()
    {
        return $this->archives;
    }

    /**
     * Get id
     *
     * @return integer 
     */
    public function getId()
    {
        return $this->id;
    }

    /**
     * Set title
     *
     * @param string $title
     * @return Archive
     */
    public function setTagName($tag_name)
    {
        $this->tag_name = $tag_name;

        return $this;
    }

    /**
     * Get title
     *
     * @return string 
     */
    public function getTagName()
    {
        return $this->tag_name;
    }


    public function setTagDesc($tag_desc)
    {
        $this->tag_desc = $tag_desc;

        return $this;
    }

    public function getTagDesc()
    {
        return $this->tag_desc;
    }

    public function __toString()
    {
        return $this->tag_name;
    }

}

src/Codersmill/ArchiveBundle/Controller/DefaultController.php
<?php

namespace Codersmill\ArchiveBundle\Controller;

use Symfony\Bundle\FrameworkBundle\Controller\Controller;
use Codersmill\ArchiveBundle\Entity\Archive;
use Symfony\Component\HttpFoundation\Request;

class DefaultController extends BaseController
{
    public function homepageAction()
    {
        $repository = $this->getDoctrine()->getRepository('CodersmillArchiveBundle:StaticPage');
        $page = $repository->findOneByLabel('Strona główna');

        return $this->render('CodersmillArchiveBundle:Default:homepage.html.twig', array('page' => $page));
    }


    public function indexAction(Request $request)
    {
        $repository = $this->getDoctrine()->getRepository('CodersmillArchiveBundle:Archive');
//        $archives = $repository->findAll();
        $archives = $repository->getAllPublicArchives();

        $archive_names = Archive::getArchiveModelNames();

        $paginator  = $this->get('knp_paginator');
        $pagination = $paginator->paginate(
            $archives,
            $request->query->get('page', 1)/*page number*/,
            10/*limit per page*/
        );

//        try {
//            $phpExcelObject = $this->get('phpexcel')->createPHPExcelObject('/var/www/teatr.dev/src/Codersmill/ArchiveBundle/Resources/public/archive2.xls');
//            $xml = $phpExcelObject;
//            $archive_xls = $phpExcelObject;
//        } catch( Exception $e) {
//            print_r($e); die;
//        }
//
//#        echo "<pre>";
//        $a = $phpExcelObject->getSheetByName('F - Fotografie');
#        var_dump($a->toArray());
#        print_r(get_class_methods($a));
#        var_dump($phpExcelObject->getSheetNames());
#        $sheet_count = $archive_xls->getSheetCount();
#        $sheet_names = $archive_xls->getSheetName();

#        print_r(get_class_methods($phpExcelObject));
#        var_dump($phpExcelObject);
#        die;
    
        return $this->render('CodersmillArchiveBundle:Default:index.html.twig', array('archives' => $archives, 'pagination' => $pagination, 'archive_names' => $archive_names));
    }
    
    public function showAction($id)
    {
        $repository = $this->getDoctrine()->getRepository('CodersmillArchiveBundle:Archive');

        $archive = $repository->find($id);
        $latest = $repository->getLatestArchives();
        $tags = $archive->getTags();

        $categories =  $archive_names = Archive::getArchiveModelNames();

        return $this->render('CodersmillArchiveBundle:Default:show.html.twig', array('archive' => $archive, 'latests' => $latest, 'archive_tags' => $tags, 'categories' => $categories));
    }

    public function tagsAction(Request $request, $name)
    {
        $repository = $this->getDoctrine()->getRepository('CodersmillArchiveBundle:Tag');

        $query = $repository->createQueryBuilder('p')
            ->where('p.tag_name = :tagname')
            ->setParameter('tagname', $name)
            ->getQuery()
            ->getResult();

        $tags = $query[0];

        $paginator  = $this->get('knp_paginator');
        $pagination = $paginator->paginate(
            $tags->getArchives(),
            $request->query->get('page', 1)/*page number*/,
            10/*limit per page*/
        );

        $archive_names = Archive::getArchiveModelNames();

        return $this->render('CodersmillArchiveBundle:Default:index.html.twig', array('pagination' => $pagination, 'archive_names' => $archive_names));

        echo '<pre>';
        var_dump($query->getResult()[0]->getArchives()->toArray());
        die;

//        $query = $repository->createQueryBuilder('c')
//            ->innerJoin('c.archive','u')
//            ->where('c.company = :company')
//            ->setParameter('company', $companyId)
//            ->orderBy('c.name', 'ASC')
//            ->getQuery();
//        $containers = $query->getResult();
    }
}

src/Codersmill/ArchiveBundle/Resources/views/Default/homepage.html.twig
{% extends '::base.html.twig' %}

{% block body -%}
<div id="primary" class="sidebar-off clearfix">
    <!-- #content -->
    <div id="content" role="main">

        <article class="page hentry clearfix">
            <!-- .hentry-box -->
            <div class="hentry-box">
                <!-- .entry-wrap -->
                <div class="entry-wrap">

                    {#<header id="page-header">#}
                        {#<h1 class="page-title">Strona główna</h1>#}
                    {#</header>#}

                    <div class="entry-content clearfix">
                        <p>{{ page.description|nl2br }}</p>
                        <div class="row" style="text-align: center; padding-top: 20px;">
                            <div class="col-md-3 col-sm-6" style="float: left; ">
                                <h4></h4>
                                <p><a href="http://www.szeptyccy.pl/" target="_blank"><img style="width: 150px; margin-bottom: 20px;" src="{{ app.request.uriForPath(asset("/images/logo3.jpg")) | replace({'/app_dev.php': ''}) | replace({'/app.php': ''}) }}" alt="Logo"/></a></p>
                            </div>
                            <div class="col-md-3 col-sm-6" style="float: left; ">
                                <h4>Przy współpracy</h4>
                                <p><a href="http://dom-komedii.pl/" target="_blank"><img style="width: 150px; margin-bottom: 20px;" src="{{ app.request.uriForPath(asset("/images/logo2.png")) | replace({'/app_dev.php': ''}) | replace({'/app.php': ''}) }}" alt="Logo"/></a></p>
                            </div>
                            <div class="col-md-3 col-sm-6" style="float: left;">
                                <h4>Przy współpracy</h4>
                                <p><img style="width: 150px; margin-bottom: 20px; padding-top: 40px;" src="{{ app.request.uriForPath(asset("/images/logo4.jpg")) | replace({'/app_dev.php': ''}) | replace({'/app.php': ''}) }}" alt="Logo"/></p>
                            </div>
                            <div class="col-md-3 col-sm-6" style="float: left; ">
                                <h4>Dofinansowano ze środków</h4>
                                <p><a href="http://www.mkidn.gov.pl/" target="_blank"><img style="width: 150px; margin-bottom: 20px;" src="{{ app.request.uriForPath(asset("/images/logo1.jpg")) | replace({'/app_dev.php': ''}) | replace({'/app.php': ''}) }}" alt="Logo"/></a></p>
                            </div>
                        </div>
                    </div>

                    <!-- /.entry-wrap -->
                </div>

                <!-- /.hentry-box -->
            </div>
        </article>

    </div>
</div>
{% endblock %}

src/Codersmill/ArchiveBundle/Resources/views/Default/index.html.twig
{% extends '::base.html.twig' %}

{% block body -%}

<div id="primary" class="sidebar-off clearfix">
    <!-- #content -->
    <div id="content" role="main">
        <div class="index">
            <div class="row">
                <div class="col-md-12" style="text-align: center;">
                    <div class="count">
                        {{ pagination.getTotalItemCount }} archiwów
                        {#<p>#}
                            {#{{ knp_pagination_sortable(pagination, 'Id', 'a.id') }}#}
                        {#</p>#}
                        {#<p>#}
                            {#{% if pagination.isSorted('a.Title') %} class="sorted"{% endif %}>{{ knp_pagination_sortable(pagination, 'Title', 'a.title') }}#}
                        {#</p>#}
                    </div>
                </div>
            </div>

            {% if (pagination is defined) and (pagination.getTotalItemCount > 0) %}
            <ul id="timeline" class="clearfix">
                {% for entity in pagination %}
                {#{% for entity in archives %}#}
                    {% include "CodersmillArchiveBundle:partials:archiveItem.html.twig" with { entity: entity } %}
                {% endfor %}
            </ul>
            {% else %}
                <div class="row archive">

                        <div class="col-md-8 col-md-offset-2 archive-info" style="padding: 20px;">

                            <div class="archive-title">
                                Brak wyników
                            </div>

                            <div class="archive-desc">
                                <div class="row">
                                    <div class="col-md-12">
                                        <h3>Niestety nic nie znaleźliśmy</h3>
                                    </div>
                                </div>
                            </div>
                        </div>
                </div>
            {% endif %}

            <div class="row">
                <div class="col-md-12" style="text-align: center;">
                    <div class="navigation">
                        {{ knp_pagination_render(pagination) }}
                    </div>
                </div>
            </div>

        </div>
    </div>
</div>

{% endblock %}

src/Codersmill/ArchiveBundle/Resources/views/Default/search.html.twig
{% extends '::base.html.twig' %}

{% block body -%}

    <div id="primary" class="sidebar-off clearfix">
        <!-- #content -->
        <div id="content" role="main">

            <article class="page hentry clearfix">
                <!-- .hentry-box -->
                <div class="hentry-box">
                    <!-- .entry-wrap -->
                    <div class="entry-wrap">

                        <header id="page-header">
                        <h1 class="page-title">Wyszukiwanie zaawansowane <span class="pull-right" id="show_advanced_options"><i class="fa fa-angle-double-down"></i></span></h1>
                        </header>

                        <div id="advanced_options" class="entry-content clearfix" style="display: none;">
                            <form method="get" id="advanced_searchform" class="advanced_searchform" action="{{ path('codersmill_archive_search') }}" role="search">
                                <label for="title">Tytuł archiwum</label>
                                <input type="search" class="field" name="title" placeholder="Tytuł" value="{{ app.request.query.get("title") }}">
                                <label for="date">Data stworznia/powstania</label>
                                <input type="search" class="field" name="date" placeholder="Data" value="{{ app.request.query.get("date") }}">
                                <label for="author">Autor dzieła</label>
                                <input type="search" class="field" name="author" placeholder="Autor" value="{{ app.request.query.get("author") }}">
                                <label for="archive_type">Kategoria archiwum</label>
                                <select name="archive_type" id="simple_select">
                                    <option value="Wszystko">
                                        Wszystko
                                    </option>
                                    {% for category in categories %}
                                        {% if category == app.request.query.get("archive_type") %}
                                            <option value="{{ category }}" selected="selected">
                                                {{ category }}
                                            </option>
                                        {% else %}
                                            <option value="{{ category }}">
                                                {{ category }}
                                            </option>
                                        {% endif %}
                                    {% endfor %}
                                </select>

                                <input type="submit" class="submit" id="searchsubmit" value="Szukaj">
                            </form>
                        </div>

                        <!-- /.entry-wrap -->
                    </div>

                    <!-- /.hentry-box -->
                </div>
            </article>

        </div>
    </div>

    <div id="primary" class="sidebar-off clearfix">
        <!-- #content -->
        <div id="content" role="main">
            <div class="index">
                <div class="row">
                    <div class="col-md-12" style="text-align: center;">
                        <div class="count">
                            {{ pagination.getTotalItemCount }} archiwów
                            {#<p>#}
                            {#{{ knp_pagination_sortable(pagination, 'Id', 'a.id') }}#}
                            {#</p>#}
                            {#<p>#}
                            {#{% if pagination.isSorted('a.Title') %} class="sorted"{% endif %}>{{ knp_pagination_sortable(pagination, 'Title', 'a.title') }}#}
                            {#</p>#}
                        </div>
                    </div>
                </div>

                {% if (pagination is defined) and (pagination.getTotalItemCount > 0) %}
                    <ul id="timeline" class="clearfix">
                        {% for entity in pagination %}
                            {#{% for entity in archives %}#}
                            {% include "CodersmillArchiveBundle:partials:archiveItem.html.twig" with { entity: entity } %}
                        {% endfor %}
                    </ul>
                {% else %}
                    <div class="row archive">

                        <div class="col-md-8 col-md-offset-2 archive-info" style="padding: 20px; text-align: center;">

                            <div class="archive-title">
                                Brak wyników
                            </div>

                            <div class="archive-desc">
                                <div class="row">
                                    <div class="col-md-12">
                                        <h3>Niestety nic nie znaleźliśmy</h3>
                                    </div>
                                </div>
                            </div>
                        </div>
                    </div>
                {% endif %}

                <div class="row">
                    <div class="col-md-12" style="text-align: center;">
                        <div class="navigation">
                            {{ knp_pagination_render(pagination) }}
                        </div>
                    </div>
                </div>

            </div>
        </div>
    </div>

    <script>
        $(document).ready(function() {
            $("select").simpleselect();
        });


        $('#show_advanced_options').click(function() {
            $('#advanced_options').slideDown('slow');
        });
    </script>

{% endblock %}

src/Codersmill/ArchiveBundle/Resources/views/Default/show.html.twig
{% extends '::base.html.twig' %}

{% block body %}

        {#<div class="row">#}
            {#<div class="archive-item">#}
                {#<div class="col-md-4">#}
                    {#<img src="http://placehold.it/300x350">#}
                {#</div>#}
                {#<div class="col-md-8 archive-info">#}
                    {#<div class="archive-title">#}
                        {#{{ archive.title }}#}
                        {#<a href="#" id="show_detail"><img src="{{ app.request.uriForPath(asset("/images/arrow-down.png")) | replace({'/app_dev.php': ''}) }}" alt="Pokaż więcej" class="pull-right"></a>#}
                    {#</div>#}

                    {#<div class="archive-desc">#}
                        {#{% if archive.description is defined %}#}
                            {#Opis: {{ archive.description }}<br><br>#}
                        {#{% endif %}#}

                        {#<div id="details" style="display: none">#}
                            {#{% if archive.scanNumber is defined %}#}
                                {#Numer skanu: {{ archive.scanNumber }}<br>#}
                            {#{% endif %}#}
                            {#{% if archive.archiveAuthor is defined %}#}
                                {#Autor: {{ archive.archiveAuthor }}<br>#}
                            {#{% endif %}#}
                            {#{% if archive.dateCreated is defined %}#}
                                {#Data: {{ archive.dateCreated }}<br>#}
                                {#&#123;&#35;|date('d/m/Y', timezone="Europe/Warsaw")&#35;&#125;#}
                            {#{% endif %}#}
                            {#{% if archive.owner is defined %}#}
                                {#Właściciel: {{ archive.owner }}<br>#}
                            {#{% endif %}#}
                            {#{% if archive.format is defined %}#}
                                {#Format: {{ archive.format }}<br>#}
                            {#{% endif %}#}
                        {#</div>#}
                    {#</div>#}
                {#</div>#}
            {#</div>#}
        {#</div>#}

    {#<script>#}
        {#$(document).ready(function() {#}

            {#$('#show_detail').on('click', function(e) {#}
                {#e.preventDefault();#}
                {#$('#details').slideDown('slow');#}
            {#});#}

        {#});#}
    {#</script>#}

		{#<hr>#}

    <section id="primary" class="sidebar-left clearfix">

        <!-- #content -->
        <div id="content" role="main">
            <article id="post-1" class="post-1 post type-post status-publish format-standard hentry category-data tag-data-2 tag-utwory clearfix">
                <!-- .hentry-box -->
                <div class="hentry-box">
                    <div class="entry-wrap">
                        <header class="entry-header">
                            <h1 class="entry-title">{{ archive.title }}</h1>
                            <div class="entry-meta"><span class="entry-meta-date"><time datetime="1793-06-20T17:49:45+00:00">{{ archive.dateCreated }}</time></span></div>
                        </header>

                        <div class="entry-content clearfix">
                            <p>{{ archive.description }}</p>
                        </div>
                        {% if (archive_tags is defined) and (archive_tags|length > 0) %}
                            <div class="tags">
                                Tagi:
                                {% for tag in archive_tags %}
                                    <a href="{{ path('codersmill_archive_tags', {'name': tag.tagName}) }}">{{ tag.tagName }}</a>
                                {% endfor %}
                            </div>
                        {% endif %}
                        <!-- /.hentry-wrap -->
                    </div>
                    <!-- /.hentry-box -->
                </div>
            </article>
        </div>
        <!-- #content -->

        <!-- #sidebar -->
        <aside id="sidebar" role="complementary">

            <div id="search-2" class="widget widget_search clearfix">
                <form method="get" id="searchform" class="searchform" action="{{ path('codersmill_archive_search') }}" role="search">
                    <label for="s" class="screen-reader-text">Search</label>
                    <input type="search" class="field" name="title" placeholder="Szukaj …">
                    <input type="submit" class="submit" id="searchsubmit" value="Search">
                </form>
            </div>
            {% if latests is defined %}
            <div id="recent-posts-2" class="widget widget_recent_entries clearfix">
                <h4 class="widget-title">Ostatnio dodane archiwa</h4>
                <ul>
                {% for latest in latests %}
                    <li>
                        <a href="{{ path('codersmill_archive_show', {'id': latest.id}) }}">{{ latest.title }}</a>
                    </li>
                {% endfor %}
                </ul>
            </div>
            {% endif %}

            {% if categories is defined %}
            <div id="categories-2" class="widget widget_categories clearfix">
                <h4 class="widget-title">Kategorie</h4>
                <ul>
                    {% for category in categories %}
                        <li class="cat-item cat-item-1">
                            <a href="{{ path('codersmill_archive_search', {'archive_type': category}) }}">{{ category }}</a>
                        </li>
                    {% endfor %}
                </ul>
            </div>
            {% endif %}
        </aside>
        <!-- /#sidebar -->

    </section>


{% endblock %}